this._wlpb=this._wlpb||{};(function(_){var window=this;
_._F_toggles_initialize=function(a){("undefined"!==typeof globalThis?globalThis:"undefined"!==typeof self?self:this)._F_toggles=a||[]};(0,_._F_toggles_initialize)([]);
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k=function(){return function(){}};
var aa=function(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length},l=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},m=function(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.I=function(d,f,e){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[f].apply(d,g)}},ba=function(a){var b=a.length;if(0<
b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},p=function(){var a=n.navigator;return a&&(a=a.userAgent)?a:""},q=function(a){return-1!=p().indexOf(a)},r=function(a){r[" "](a);return a},ca=function(a,b){for(var c in a)b.call(void 0,a[c],c,a)},ea=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<da.length;e++)c=da[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},ha=function(a,b){ca(b,function(c,d){"style"==d?a.style.cssText=
c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:fa.hasOwnProperty(d)?a.setAttribute(fa[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},ja=function(a,b,c){function d(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(var f=2;f<c.length;f++){var e=c[f];if(!aa(e)||l(e)&&0<e.nodeType)d(e);else{a:{if(e&&"number"==typeof e.length){if(l(e)){var g="function"==typeof e.item||"string"==typeof e.item;break a}if("function"===typeof e){g="function"==
typeof e.item;break a}}g=!1}ia(g?ba(e):e,d)}}},ka=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},t=function(){this.g=n.document||document},v=function(a,b,c){Array.isArray(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(u||(c={},u=(c.atomic=!1,c.autocomplete="none",c.dropeffect="none",c.haspopup=!1,c.live="off",c.multiline=!1,c.multiselectable=!1,c.orientation="vertical",c.readonly=!1,c.relevant="additions text",c.required=!1,
c.sort="none",c.busy=!1,c.disabled=!1,c.hidden=!1,c.invalid="false",c)),c=u,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)},w=function(a){return"string"==typeof a.className?a.className:a.getAttribute&&a.getAttribute("class")||""},la=function(a,b){"string"==typeof a.className?a.className=b:a.setAttribute&&a.setAttribute("class",b)},x=function(a,b){a.classList?b=a.classList.contains(b):(a=a.classList?a.classList:w(a).match(/\S+/g)||[],b=0<=ma(a,b));return b},oa=function(){var a=
y,b=na;a.classList?a.classList.remove(b):x(a,b)&&la(a,Array.prototype.filter.call(a.classList?a.classList:w(a).match(/\S+/g)||[],function(c){return c!=b}).join(" "))},pa=k(),z=function(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1},A=function(a,b){z.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType=
"";this.i=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;if(b=a.relatedTarget){if(qa){a:{try{r(b.nodeName);var f=!0;break a}catch(e){}f=!1}f||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=
void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:ra[a.pointerType]||"";this.state=a.state;this.i=a;a.defaultPrevented&&A.B.h.call(this)}},ta=function(a,b,c,d,f){this.listener=a;this.proxy=
null;this.src=b;this.type=c;this.capture=!!d;this.s=f;this.key=++sa;this.m=this.o=!1},B=function(a){a.m=!0;a.listener=null;a.proxy=null;a.src=null;a.s=null},C=function(a){this.src=a;this.g={};this.h=0},D=function(a,b){var c=b.type;if(c in a.g){var d=a.g[c],f=ma(d,b),e;(e=0<=f)&&Array.prototype.splice.call(d,f,1);e&&(B(b),0==a.g[c].length&&(delete a.g[c],a.h--))}},E=function(a,b,c,d){for(var f=0;f<a.length;++f){var e=a[f];if(!e.m&&e.listener==b&&e.capture==!!c&&e.s==d)return f}return-1},F=function(a,
b,c,d,f){if(d&&d.once)ua(a,b,c,d,f);else if(Array.isArray(b))for(var e=0;e<b.length;e++)F(a,b[e],c,d,f);else c=G(c),a&&a[H]?a.j.add(String(b),c,!1,l(d)?!!d.capture:!!d,f):va(a,b,c,!1,d,f)},va=function(a,b,c,d,f,e){if(!b)throw Error("a");var g=l(f)?!!f.capture:!!f,h=wa(a);h||(a[xa]=h=new C(a));c=h.add(b,c,d,g,e);if(!c.proxy){d=ya();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)za||(f=g),void 0===f&&(f=!1),a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(Aa(b.toString()),
d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("b");Ba++}},ya=function(){function a(c){return b.call(a.src,a.listener,c)}var b=Ca;return a},ua=function(a,b,c,d,f){if(Array.isArray(b))for(var e=0;e<b.length;e++)ua(a,b[e],c,d,f);else c=G(c),a&&a[H]?a.j.add(String(b),c,!0,l(d)?!!d.capture:!!d,f):va(a,b,c,!0,d,f)},Da=function(a,b,c,d,f){if(Array.isArray(b))for(var e=0;e<b.length;e++)Da(a,b[e],c,d,f);else(d=l(d)?!!d.capture:!!d,c=G(c),a&&a[H])?(a=a.j,b=String(b).toString(),
b in a.g&&(e=a.g[b],c=E(e,c,d,f),-1<c&&(B(e[c]),Array.prototype.splice.call(e,c,1),0==e.length&&(delete a.g[b],a.h--)))):a&&(a=wa(a))&&(b=a.g[b.toString()],a=-1,b&&(a=E(b,c,d,f)),(c=-1<a?b[a]:null)&&Ea(c))},Ea=function(a){if("number"!==typeof a&&a&&!a.m){var b=a.src;if(b&&b[H])D(b.j,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Aa(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ba--;(c=wa(b))?(D(c,a),0==c.h&&(c.src=
null,b[xa]=null)):B(a)}}},Aa=function(a){return a in Fa?Fa[a]:Fa[a]="on"+a},Ca=function(a,b){if(a.m)a=!0;else{b=new A(b,this);var c=a.listener,d=a.s||a.src;a.o&&Ea(a);a=c.call(d,b)}return a},wa=function(a){a=a[xa];return a instanceof C?a:null},G=function(a){if("function"===typeof a)return a;a[Ga]||(a[Ga]=function(b){return a.handleEvent(b)});return a[Ga]},I=function(){this.j=new C(this);this.G=this},Ia=function(a){var b=a.G;a="change";var c=a.type||a;if("string"===typeof a)a=new z(a,b);else if(a instanceof
z)a.target=a.target||b;else{var d=a;a=new z(c,b);ea(a,d)}b=a.g=b;Ha(b,c,!0,a);Ha(b,c,!1,a)},Ha=function(a,b,c,d){if(b=a.j.g[String(b)]){b=b.concat();for(var f=!0,e=0;e<b.length;++e){var g=b[e];if(g&&!g.m&&g.capture==c){var h=g.listener,fb=g.s||g.src;g.o&&D(a.j,g);f=!1!==h.call(fb,d)&&f}}}},J=k(),L=function(a){I.call(this);this.u=a||K||(K=new t);this.D=!1;this.i=null},Ja=function(){I.call(this)},M=function(a){L.call(this,a);this.v=new Ja;F(this.v,"change",this.H,!1,this)},Na=function(){var a=Ka,b=
a.v,c=La;c=Math.round(c);b.g!=c&&(b.g=100<c?100:0>c?0:c,Ia(b));a.h()&&Ma(a)},Ma=function(a){var b=a.h();v(b,"valuenow",Math.round(a.v.g))};var n=this||self,Oa=n._F_toggles||[];var K;var ma=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ia=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in d&&b.call(void 0,d[f],f,a)};var Pa=!!(Oa[0]&256);var Qa;if(Oa[0]&128)Qa=Pa;else{var N;a:{for(var Ra=["WIZ_global_data","oxN3nb"],O=n,Sa=0;Sa<Ra.length;Sa++)if(O=O[Ra[Sa]],null==O){N=null;break a}N=O}var Ta=N&&N[610401301];Qa=null!=Ta?Ta:!1}var Ua=Qa;var P,Va=n.navigator;P=Va?Va.userAgentData||null:null;r[" "]=k();var Wa=Ua&&P&&0<P.brands.length?!1:q("Opera"),Q=Ua&&P&&0<P.brands.length?!1:q("Trident")||q("MSIE"),Xa=q("Edge"),qa=q("Gecko")&&!(-1!=p().toLowerCase().indexOf("webkit")&&!q("Edge"))&&!(q("Trident")||q("MSIE"))&&!q("Edge"),Ya=-1!=p().toLowerCase().indexOf("webkit")&&!q("Edge"),Za;
a:{var $a="",ab=function(){var a=p();if(qa)return/rv:([^\);]+)(\)|;)/.exec(a);if(Xa)return/Edge\/([\d\.]+)/.exec(a);if(Q)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ya)return/WebKit\/(\S+)/.exec(a);if(Wa)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ab&&($a=ab?ab[1]:"");if(Q){var R,bb=n.document;R=bb?bb.documentMode:void 0;if(null!=R&&R>parseFloat($a)){Za=String(R);break a}}Za=$a}var cb=Za;var da="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");var fa={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};t.prototype.h=k();t.prototype.i=function(a,b,c){var d=this.g,f=arguments,e=f[1],g=ka(d,String(f[0]));e&&("string"===typeof e?g.className=e:Array.isArray(e)?g.className=e.join(" "):ha(g,e));2<f.length&&ja(d,g,f);return g};var u;z.prototype.h=function(){this.defaultPrevented=!0};var za=function(){if(!n.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=k();n.addEventListener("test",c,b);n.removeEventListener("test",c,b)}catch(d){}return a}();m(A,z);var ra={2:"touch",3:"pen",4:"mouse"};A.prototype.h=function(){A.B.h.call(this);var a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};var H="closure_listenable_"+(1E6*Math.random()|0);var sa=0;C.prototype.add=function(a,b,c,d,f){var e=a.toString();a=this.g[e];a||(a=this.g[e]=[],this.h++);var g=E(a,b,d,f);-1<g?(b=a[g],c||(b.o=!1)):(b=new ta(b,this.src,e,!!d,f),b.o=c,a.push(b));return b};var xa="closure_lm_"+(1E6*Math.random()|0),Fa={},Ba=0,Ga="__closure_events_fn_"+(1E9*Math.random()>>>0);m(I,pa);I.prototype[H]=!0;I.prototype.removeEventListener=function(a,b,c,d){Da(this,a,b,c,d)};J.g=void 0;J.h=function(){J.g||(J.g=new J)};m(L,I);J.h();L.prototype.h=function(){return this.i};L.prototype.F=function(){this.i=ka(this.u.g,"DIV")};L.prototype.C=function(){this.D=!0};m(Ja,I);Ja.prototype.g=0;m(M,L);var db={vertical:"progress-bar-vertical",horizontal:"progress-bar-horizontal"};M.prototype.F=function(){this.g=this.u.i("DIV","progress-bar-thumb");this.i=this.u.i("DIV",db[this.l],this.g);Ma(this);var a=this.h();v(a,"valuemin",0);a=this.h();v(a,"valuemax",100)};M.prototype.C=function(){M.B.C.call(this);Q&&7>cb&&F(this.h(),"resize",this.A,!1,this);this.A();var a=this.h();a.setAttribute("role","progressbar");v(a,"live","polite")};M.prototype.l="horizontal";
M.prototype.H=function(){this.A();Ia(this)};M.prototype.A=function(){if(this.g){var a=Math.round(this.v.g)/100,b=Math.round(100*a);"vertical"==this.l?Q&&7>cb?(this.g.style.top="0",this.g.style.height="100%",b=this.g.offsetHeight,a=Math.round(a*b),this.g.style.top=b-a+"px",this.g.style.height=a+"px"):(this.g.style.top=100-b+"%",this.g.style.height=b+"%"):this.g.style.width=b+"%"}};var La=10,eb=window.document,gb=window;"undefined"===typeof window._docs_flag_initialData&&(eb=window.parent.document,gb=window.parent);var hb=eb.getElementById("waffle-loading-progress-bar-overlay"),Ka=new M(K||(K=new t)),S=Ka;
if("horizontal"!=S.l){var na=db[S.l],T=db.horizontal;S.l="horizontal";var y=S.h();if(y){if(x(y,na)){oa();var U=y;if(U.classList)U.classList.add(T);else if(!x(U,T)){var ib=w(U);la(U,ib+(0<ib.length?" "+T:T))}}var V=S.g.style;"vertical"==S.l?(V.left="0",V.width="100%"):(V.top=V.left="0",V.height="100%");S.A()}}Na();if(null!=hb){var W=Ka;if(W.D)throw Error("c");W.i||W.F();hb?hb.insertBefore(W.i,null):W.u.g.body.appendChild(W.i);W.C()}
var jb=setInterval(function(){80>=La&&(La+=10,Na())},300),X=["waffleProgressBarInterval"],Y=gb||n;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===jb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=jb;
})(this._wlpb);
// Google Inc.

//# sourceMappingURL=waffleloadingprogressbar_core.sourcemap
