module_names = {
            'saladbox': 'saladboxScraper',
            'takeandeat': 'takeandeatScraper',
            'sandra': 'sandraScraper',
            'zucchetti': 'zucchettiScraper',
            'urbio': 'urbioScraper',
            'velpitar': 'velpitarScraper',
            'zeelandia': 'zeelandiaScraper',
            # 'typingdna': 'typingdnaScraper',
            'trencadis': 'trencadisScraper',
            'tcandc': 'tcandcScraper',
            'titanmachinery': 'titanmachineryScraper',
            'splendor': 'splendorScraper',
            'speedservicesatumare': 'speedservicesatumareScraper',
            'sonrisatechnologies': 'sonrisatechnologiesScraper',
            'softing': 'softingScraper',
            'softexco': 'softexcoScraper',
            'signaliduna': 'signalidunaScraper',
            'sephora': 'sephoraScraper',
            'secondtex': 'secondtexScraper',
            'rervest': 'rervestScraper',
            # 'reinert': 'reinertScraper',
            'rdnautomatic': 'rdnautomaticScraper',
            'ramadaiasi': 'ramadaiasiScraper',
            'polipolmobila': 'polipolmobilaScraper',
            'pago': 'PagoScraper',
            'oradeatechhub': 'oradeatechhubScraper',
            'panifcom': 'panifcomScraper',
            'nolimits': 'NolimitsScraper',
            'nokia': 'nokiaScraper',
            'nielseniq': 'nielseniqScraper',
            # 'netrom': 'NetromScraper', 
            'nagarro': 'NagarroScraper',
            'metamob': 'metamobScraper',
            'leier': 'leierScraper',
            'kinetic': 'kineticScraper',
            'kimballelectronics': 'kimballelectronicsScraper',
            # 'kaizengaming': 'KaizenGamingScraper',
            'interbrandsorbico': 'InterbrandsOrbicoScraper',
            'inova': 'inovagroupScraper',
            'iasidelivery': 'iasideliveryScraper',
            'htecgroup': 'htecgroupScraper',
            'gazduirejocuri': 'GazduireJocuriScraper',
            'expomedics': 'expomedicsScraper',
            'etusoft': 'etusoftScraper',
            'ensemblesoftware': 'ensemblesoftwareScraper',
            'elytishospital': 'elytishospitalScraper',
            'ellisium': 'ellisiumScraper',
            'electra': 'electraScraper',
            'edutrust': 'edutrustScraper',
            'duktech': 'duktechScraper',
            'dualit': 'dualitScraper',
            'csgroup': 'CSGroupScraper',
            'cscale': 'CScaleScraper',
            'iuliuscompany': 'iuliuscompanyScraper',
            'creatopy': 'CreatopyScraper',
            'covalact': 'covalactScraper',
            'consultmed': 'consultmedScraper',
            'connectgroup': 'connectgroupScraper',
            'conexdist': 'conexdistScraper',
            'cgm': 'CGMScraper',
            'casaautoiasi': 'casaautoiasiScraper',
            'britishcouncil': 'britishcouncilScraper',
            'carturesti': 'carturestiScraper',
            'cargus': 'CargusScraper',
            'cargotrack': 'cargotrackScraper',
            'careerscenter': 'careerscenterScraper',
            'calcrom': 'calcromScraper',
            # 'brillio': 'brillioScraper',
            'bitsoftware': 'BitSoftwareScraper',
            'expertmind': 'expertmindScraper',
            'beenear': 'BeenearScraper',
            'bbcollection': 'bbcollectionScraper',
            'basware': 'baswareScraper',
            'bakertilly': 'bakertillyScraper',
            'avaelgo': 'avaelgoScraper',
            'autosiena': 'autosienaScraper',
            'autonet': 'autonetScraper',
            'autoclass': 'autoclassScraper',
            'atpgroup': 'atpgroupScraper',
            'artvertising': 'artvertisingScraper',
            # 'apavital': 'apavitalScraper',
            'anahr': 'anahrScraper',
            'allengra': 'allengraScraper',
            # 'aeroportoradea': 'aeroportoradeaScraper',
            'ppromania': 'ppromaniaScraper',
            'expresscredit': 'expresscreditScraper',
            'arcadiamedical': 'arcadiamedicalScraper',
            # 'mennekes': 'mennekesScraper',
            'sinaps': 'sinapsScraper',
            'affidearomania': 'affidearomaniaScraper',
            'pimcopy': 'pimcopyScraper',
            'canopy': 'canopyScraper',
            'dentesse': 'dentesseScraper',
            'verla': 'verlaScraper',
            'eurotech': 'eurotechScraper',
            # 'bras': 'brasScraper', REMOVED FROM TESTS UNTIL COMPANY FILTER IS ADDED
            'ipso': 'ipsoScraper',
            'bioclinica': 'bioclinicaScraper',
            'vetro': 'vetroScraper',
            'urbica': 'urbicaScraper',
            'noodlepack': 'noodlepackScraper',
            
            # Add more module names as needed
            }